### ISSUE TITLE
Growing routes and dtrace log on mutliple requires

### ISSUE THREAD

**Issue by bthibault** [restify/node-restify#725]
Came across this by doing something like this: 

```
/* index.js */
// load external route, before other routing occurs
server.pre(function(req,res,next){
     try{
     // should be safe because require caches
     require('./controllers/test')(server); 
    }catch(e){
       console.log(e);
    }
});

/* controllers/test.js */ 
module.exports = function(server) {
    server.get('/test', function(req,res){
       console.log('found');
        res.send('found');
       //return next();
   });

    // not a valid method trigger an error 
    server.delete('/test', function(req,res){
       // no-op
    });
 };
```

with a few calls to /test 

I end up spitting out: [TypeError: Object   Accepts: application/json, text/plain, application/octet-stream, application/javascript
    Name: restify
    Pre: [function]
    Router: RestifyRouter:
        DELETE: []
        GET: [gettest, gettest9cad33b, gettest3b4e5a1, gettest1dea0e2, gettest1d726cb, getteste5f7298, gettest0c801e6, gettest9f8b903, gettestf7bcc1b]
        HEAD: []
        OPTIONS: []
        PATCH: []
        POST: []
        PUT: []

```
Routes: 
    gettest: [initialize, authenticate, function, function]
    gettest9cad33b: [initialize, authenticate, function, function]
    gettest3b4e5a1: [initialize, authenticate, function, function]
    gettest1dea0e2: [initialize, authenticate, function, function]
    gettest1d726cb: [initialize, authenticate, function, function]
    getteste5f7298: [initialize, authenticate, function, function]
    gettest0c801e6: [initialize, authenticate, function, function]
    gettest9f8b903: [initialize, authenticate, function, function]
    gettestf7bcc1b: [initialize, authenticate, function, function]
Secure: false
Url: http://0.0.0.0:8000
Version: 
```

 has no method 'delete']

the Routes keeps growing and growing, my concern is  eventually with enough calls to /test this will crash the server with an out of memory error 

That said it appears I can't load external routes using .pre() ... the preferred way is load them once, although require() should be cached and idempotent so I was expecting a penalty to multiple requires() 

Thanks
